# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ctest19',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/ctest19',
                'lib_path': 'ctest19'},
  'syms': {'ctest19.core': {'ctest19.core.foo': ('core.html#foo', 'ctest19/core.py')}}}
